---
name: 'php-linter'
description: 'php-linter by pipeline components'
author: 'Robbert Müller <spam.me@grols.ch>'
branding:
  icon: 'play-circle'
  color: 'green'
inputs:
  directory:
    description: 'Directory to lint'
    required: false
    default: .
  options:
    description: 'Additional options'
    required: false
    default: ~
runs:
  using: 'docker'
  image: docker://pipelinecomponents/php-linter:edge
  args:
    - parallel-lint
    - '${{ inputs.options }}'
    - '${{ inputs.directory }}'
