---
name: 'php-linter'
description: 'php-linter by pipeline components'
author: 'Robbert Müller <spam.me@grols.ch>'
branding:
  icon: 'play-circle'
  color: 'green'
inputs:
  directory:
    description: 'Directory to lint'
    required: false
    default: .
  options:
    description: 'Additional options'
    required: false
    default: ''
runs:
  using: 'docker'
  image: docker://registry.gitlab.com/pipeline-components/yamllint/amd64:08387c500f0294fd9335eac6ac48d9124e7c9c7d
  args:
    - parallel-lint
    - '${{ inputs.options }}'
    - '${{ inputs.directory }}'
