name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      container: 
        image: pipelinecomponents/yamllint:latest
      run: yamllint action.yml
  lint-php:
    runs-on: ubuntu-18.04
    container:
      image: pipelinecomponents/php-linter:latest 
    steps:
      - uses: actions/checkout@v1
      - name: Lint php
        run: parallel-lint --colors .
      
