name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: pipelinecomponents/yamllint:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: yamllint action.yml
  lint-php:
    runs-on: ubuntu-18.04
    container:
      image: pipelinecomponents/php-linter:edge
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: touch dummy.php
      - name: Lint php
        run:  parallel-lint --colors .
  php-linter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: mjrider/phplinter@master
