name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: pipelinecomponents/yamllint:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: yamllint action.yml
  lint-php:
    runs-on: ubuntu-18.04
    container:
      image: registry.gitlab.com/pipeline-components/yamllint/amd64:08387c500f0294fd9335eac6ac48d9124e7c9c7d
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: touch dummy.php
      - name: Lint php
        run:  parallel-lint --colors .
  php-linter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: mjrider/phplinter@master
